name: Daily Append Apps

on:
  schedule:
    - cron: '10 1 * * *'   # 每天 09:10 北京时间（UTC+8）
  workflow_dispatch:

permissions:
  contents: write

jobs:
  append:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Append 3-5 apps from backlog
        run: node .github/scripts/daily_append.mjs

      - name: Commit & push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add apps.json backlog.json
          git commit -m "chore: daily append apps" || echo "No changes"
          git push

      - name: Trigger Pages deploy
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'pages.yml',
              ref: '${{ github.ref_name }}'
            })
