name: Daily Append Apps

on:
  schedule:
    - cron: '10 1 * * *'   # 每天 09:10 (北京)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  append:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Append 3–5 apps
        run: node .github/scripts/daily_append.mjs

      - name: Commit & push if changed
        run: |
          if git diff --quiet; then
            echo "No changes"; exit 0; fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add apps.json backlog.json
          git commit -m "chore: daily append apps"
          git pull --rebase origin ${{ github.ref_name }}
          git push
